spring.application.name=job-tracker-backend
spring.datasource.url=jdbc:mysql://localhost:3306/jobtracker
spring.datasource.username=root
spring.datasource.password=root123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=${JWT_SECRET:a8F#kL92!xPq7$zR0vBnT4@wYcM1HsUe}